-- ============================================================
-- PART 1: DROP SEMUA TABLE
-- Jalankan DULUAN sebelum Part 2
-- ============================================================

DROP TABLE IF EXISTS "SponsorBanner" CASCADE;
DROP TABLE IF EXISTS "SponsoredPrize" CASCADE;
DROP TABLE IF EXISTS "TournamentSponsor" CASCADE;
DROP TABLE IF EXISTS "PlayerAchievement" CASCADE;
DROP TABLE IF EXISTS "Achievement" CASCADE;
DROP TABLE IF EXISTS "PlayerPoint" CASCADE;
DROP TABLE IF EXISTS "CmsCard" CASCADE;
DROP TABLE IF EXISTS "CmsSection" CASCADE;
DROP TABLE IF EXISTS "CmsSetting" CASCADE;
DROP TABLE IF EXISTS "PlayerSkin" CASCADE;
DROP TABLE IF EXISTS "Skin" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "PlayoffMatch" CASCADE;
DROP TABLE IF EXISTS "LeagueMatch" CASCADE;
DROP TABLE IF EXISTS "ClubMember" CASCADE;
DROP TABLE IF EXISTS "Club" CASCADE;
DROP TABLE IF EXISTS "ClubProfile" CASCADE;
DROP TABLE IF EXISTS "Donation" CASCADE;
DROP TABLE IF EXISTS "TournamentPrize" CASCADE;
DROP TABLE IF EXISTS "Participation" CASCADE;
DROP TABLE IF EXISTS "Match" CASCADE;
DROP TABLE IF EXISTS "TeamPlayer" CASCADE;
DROP TABLE IF EXISTS "Team" CASCADE;
DROP TABLE IF EXISTS "Tournament" CASCADE;
DROP TABLE IF EXISTS "Season" CASCADE;
DROP TABLE IF EXISTS "Player" CASCADE;
DROP TABLE IF EXISTS "Admin" CASCADE;
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;
